Update openshift.yml 13

diff --git a/.github/workflows/openshift.yml b/.github/workflows/openshift.yml
--- a/.github/workflows/openshift.yml
+++ b/.github/workflows/openshift.yml
@@ -190,15 +190,15 @@ jobs:
         port: ${{ env.APP_PORT }}
         cleanup: false
 
-    # - name: Print application URL
-    #   env:
-    #     ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
-    #     SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
-    #   run: |
-    #     [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
-    #     echo
-    #     echo "======================== Your application is available at: ========================"
-    #     echo ${{ env.ROUTE }}
-    #     echo "==================================================================================="
+    - name: Print application URL
+      env:
+        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
+        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
+      run: |
+        [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
+        echo
+        echo "======================== Your application is available at: ========================"
+        echo ${{ env.ROUTE }}
+        echo "==================================================================================="
     #     echo
     #     echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
